name: Generate functions
on: push 
jobs:
  generate:
    runs-on: ubuntu-24.04
    steps:
      - run: printenv | grep '_FUNC'
        env:
          FORMAT_FUNC: ${{ format('{0}, {1}', 'Hi', 'world') }}
          JOIN_FUNC: ${{ join(github.event.*.html_url, ', ') }}
